[workspace]
members = [
    "crates/Utensil/utensil-daemon",
    "crates/pm",
]
resolver = "2"

[workspace.dependencies]
coreshift-core       = "1.2.13"
coreshift-foreground = "0.1.5"
utensil-ds           = "0.1.2"
utensil-wd           = "0.1.1"
utensil-bs           = "0.1.1"
utensil-pm           = { path = "crates/pm" }
