[workspace]
members = [
    "crates/Utensil/utensil-daemon",
    "crates/pm",
    "crates/dynamic_rr",
]
resolver = "2"

[workspace.dependencies]
coreshift-core       = "1.2.14"
coreshift-foreground = "0.1.11"
utensil-ds           = "0.1.3"
utensil-wd           = "0.1.3"
utensil-bs           = "0.1.2"
utensil-pm           = { path = "crates/pm" }
dynamic-rr           = { path = "crates/dynamic_rr" }
